### ISSUE TITLE
Bug with time zone.

### ISSUE THREAD

**Issue by adaleorion** [JuniorsJava/gamification#102]
I don't  send new daily in 08.06.2017 00.15
all my message add to old daily 07.06.2017

**Comment by VadimDyachenko** [comment]
@danilkuznetsov Тайм зона одна у сервисов, БД и твоего slack чата? Проверь не выставлены ли где-либо часы в UTC. Очень похоже на смещение часовых зон. Какое время было у ачивки от 07.06.2017 в БД?

**Comment by adaleorion** [comment]
спасибо @VadimDyachenko,  вчера вместе разобрались с багой,
необходимо правильно настроить time zone в jvm.

**Comment by adaleorion** [comment]
добавил правильную зону при запуске, надо проверить

**Comment by OlgaKulikova** [comment]
@danilkuznetsov Was it checked?
