### ISSUE TITLE
Acceptance tests on Java

### ISSUE THREAD

**Issue by OlgaKulikova** [JuniorsJava/gamification#17]
Implement clear acceptance tests  that could show all implemented funtionality (all requests-responses).

**Comment by OlgaKulikova** [comment]
Use library of lukas-krecan. Show in console input and output data.

**Comment by OlgaKulikova** [comment]
Can we do something with ordering of elements in result array? Because tests could fail sometimes or even always.

**Comment by OlgaKulikova** [comment]
There is only one example tests. Others acceptence tests are also needed. Maybe someone else will take this task.

**Comment by adaleorion** [comment]
@OlgaKulikova

1. пофиксил проблему с порядком в json (для проверки в одном из expectedJson специально поменял порядок в json)
2. добавил проверку второго url (/user/achieveDetails)

PS
увидел TODO c аналогичной проблемой о порядке в json в других тестах,
для ее решения предлагаю использовать либу от lukas, пока она очень хорошо справляется с этим

**Comment by OlgaKulikova** [comment]
@danilkuznetsov Супер! Нужно еще дописать acceptance тесты на все остальные энд поинты. Можешь отдать задачу ребятам, будут делать по аналогии. Просто сними ассайн и положи в беклог. Если хочешь)))

**Comment by adaleorion** [comment]
Да так и сделаю
Ребята, нужно закончить написание тестов для всех остальных endpoint по аналогии
