### ISSUE TITLE
Implement PointType Thanks

### ISSUE THREAD

**Issue by OlgaKulikova** [JuniorsJava/gamification#21]
For every type of point create new method in Controller. All business logic should be in Service layer.

**Comment by Garazd** [comment]
Assign me

**Comment by OlgaKulikova** [comment]
- [x] To create a chain in Controller - Service - Repository about Thanks achievement. In Controller url should be /achieve/thanks.

- [x] In Service to check:

- 1 thanks to 1 unique user

- maximum 2 thanks per day

- at the moment of adding the second thanks to add automatically the third thanks to user, who was userFrom of the first and second thanks.

- [x] Add check userTo != userFrom (you can't send thanks to yourself)

- [x] Tests.

**Comment by OlgaKulikova** [comment]
Добавила в список проверку - нельзя спасибку самому себе (не автомат)

**Comment by Garazd** [comment]
Исправил тесты, добавил тестирование на бросание ошибок.
