### ISSUE TITLE
Create and support Readme file

### ISSUE THREAD

**Issue by OlgaKulikova** [JuniorsJava/gamification#3]
How to set Mongo DB.
How to build and run app.
Name used technologies.

**Comment by ghost** [comment]
Add after the 2 clause:

Set up the MongoDB environment.
MongoDB requires a data directory to store all data. MongoDB’s default data directory path is \data\db. Before the first usage, you should create this folder. For more information visit https://docs.mongodb.com/getting-started/shell/installation/

**Comment by OlgaKulikova** [comment]
@BaHo1984 Thanks!
