### ISSUE TITLE
@ExceptionHandler and Json Body

### ISSUE THREAD

**Issue by OlgaKulikova** [JuniorsJava/gamification#40]
Add to controllers this annotation and Json Body for errors (status, error code (from Tech.req. doc),  message etc.)

**Comment by OlgaKulikova** [comment]
- [ ] Find all errors from Tech.req. and handle them in handler. (with custom error codes)

- [ ] Add the most common REST Exception Handler methods.

**Comment by adaleorion** [comment]
@OlgaKulikova
Привет, посмотри пожалуйста, пойдет такая обработка стандартных исключений spring
+ 
подскажи что имелось виду в этом пункте 
Find all errors from Tech.req. and handle them in handler. (with custom error codes)

**Comment by OlgaKulikova** [comment]
@danilkuznetsov В доке с ТЗ в каждом месте, где должны бросаться кастомные эксепшены стоит ссылка на букмарк. Значит в том месте кода надо бросить эксепшен, который будет хендлиться по кастомному эррор коду - он равен коду фичи. В ТЗ это все описано. Если не разберешься - пиши, обсудим.
