### ISSUE TITLE
Update Wiki

### ISSUE THREAD

**Issue by OlgaKulikova** [JuniorsJava/gamification#59]
API should be up-to-date.

**Comment by OlgaKulikova** [comment]
@starikivan Please find more convenient and readable format for API description. The current version takes too much place.
You can find examples from other repositories in github.

**Comment by OlgaKulikova** [comment]
@starikivan Well done! I think you can remove old version.
And please let's  try to write json body in readable format when one pair key-value in one string, the second pair - the second string etc. Maybe it would be better.
And let's think about if it nessesay to write not only request body but also response body. We'll discuss it.

**Comment by petrokramar** [comment]
I've changed format of json body (one pair of parameters in one string). Examples of documents and responce body were added.

**Comment by OlgaKulikova** [comment]
Good!
