### ISSUE TITLE
Change feature of Keepers

### ISSUE THREAD

**Issue by OlgaKulikova** [JuniorsJava/gamification#99]

**Comment by VadimDyachenko** [comment]
@OlgaKulikova Решили оставлять Киперов в геймификации как ачивку. Нужно будет модифицировать код к третьему релизу под новый микросервис киперов (запрос на список активных киперов, кому раздавать ачивку)

**Comment by OlgaKulikova** [comment]
The sequence is **Cron -> Gamification  -> give me all active keepers -> Keepers -> Gamification -> create achivements to all active keepers -> Database.**

**Comment by OlgaKulikova** [comment]
Cron could be implement with Spring Scheduler.
